version: '3.1'

services:
  mysql:
    platform: linux/amd64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_PORT_OUTPUT}:${MYSQL_PORT}
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
